### ISSUE TITLE
WeChatAPIError: refresh_token missing

### ISSUE THREAD

**Issue by mengkeys** [node-webot/wechat-oauth#26]
## 逻辑流程
1. 获取授权登录
2. 获取code
3. 使用code获取access_token信息
4. 再使用openid获取用户基本信息
5. 将用户信息存入mongodb数据库中
6. 路由到用户真实请求的处理中

## 问题描述
原来使用默认的内存存储access_token没有问题现在要部署到线上，将token数据存放到mongodb中，在初始化OAuth的时候传入两个函数，进行token的存和取，也没有问题，但流程走到获取用户信息那步就报了错误

## 错误信息
```
{ WeChatAPIError: refresh_token missing, hints: [ req_id: ma.bBA0101s111 ]
    at F:\node\longshanyuan\node_modules\.1.1.1@wechat-oauth\lib\util.js:15:13
    at done (F:\node\longshanyuan\node_modules\.2.7.0@urllib\lib\urllib.js:386:5)
    at F:\node\longshanyuan\node_modules\.2.7.0@urllib\lib\urllib.js:605:9
    at decodeContent (F:\node\longshanyuan\node_modules\.2.7.0@urllib\lib\urllib.js:454:14)
    at IncomingMessage.<anonymous> (F:\node\longshanyuan\node_modules\.2.7.0@urllib\lib\urllib.js:570:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) name: 'WeChatAPIError', code: 41003 }
```

## 相关资料
查阅[微信官方文档]()后得知的错误说明

|   错误码 | 错误说明 |
|   ---  |  --- |
| 41003 | 缺少refresh_token参数 |

## 疑问
是不是在存入token的时候要连同refresh_token一起写入？

**Comment by mengkeys** [comment]
设置Token的时候直接将微信返回的数据完全存入数据库，获取Token的时候也将整个记录返回即可！

**Comment by JacksonTian** [comment]
? 解决了？

**Comment by mengkeys** [comment]
@JacksonTian 必须解决了

**Comment by mengkeys** [comment]
@JacksonTian 

附上全局维护AccessToken的示例代码

Mongodb|mongoose

``` js
var TokenSchema = new Schema({
    access_token: String,
    expires_in: Number,
    refresh_token: String,
    openid: String,
    scope: String,
    create_at: String
});
```
自定义getToken方法
```js
TokenSchema.statics.getToken = function (openid, cb) {
    this.findOne({openid:openid}, function (err, result) {
        if(err) throw err;
        return cb(null, result);
    });
};
```

自定义saveToken方法
```js
TokenSchema.statics.setToken = function (openid, token, cb) {
    // 有则更新，无则添加
    this.update({openid:openid},token,{upsert:true}, function (err, result) {
        if(err) throw err;
        return cb(null);
    });
};

mongoose.model('Token', ‘TokenSchema’);
```
初始化：

```js
var client = new OAuth(appid, secret, function (openid, callback) {
    // 传入一个根据openid获取对应的全局token的方法
    // 在getUser时会通过该方法来获取token
    Token.getToken(openid, callback);
}, function (openid, token, callback) {
    // 请将token存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
    // 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
    // 持久化时请注意，每个openid都对应一个唯一的token!
    Token.setToken(openid, token, callback);
})

```
MySQL:

建表SQL
```sql
CREATE TABLE `token` (
  `access_token` varchar(107) COLLATE utf8_bin NOT NULL COMMENT '令牌',
  `expires_in` varchar(10) COLLATE utf8_bin NOT NULL COMMENT '有效期',
  `refresh_token` varchar(107) COLLATE utf8_bin NOT NULL COMMENT '刷新参数',
  `openid` varchar(28) COLLATE utf8_bin NOT NULL COMMENT '用户编号',
  `scope` varchar(50) COLLATE utf8_bin NOT NULL COMMENT '作用域',
  `create_at` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '令牌建立时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='微信令牌表';
```
设置openid为唯一索引
```sql
--
ALTER TABLE `token`
  ADD UNIQUE  KEY `openid` (`openid`);
```

使用实例
```js
var oauthApi = new Oauth(option.appId, option.appSecret,function (openid, callback) {
    return db.query('SELECT * FROM token WHERE openid = ?', [openid], function (err, result) {
        if(err) {
            return callback(err);
        }
        return callback(null, result[0]);
    });
}, function (openid, token, callback) {
    return db.query('REPLACE INTO token(access_token, expires_in, refresh_token, openid, scope, create_at) VALUES(?,?,?,?,?,?)',
        [token.access_token, token.expires_in, token.refresh_token, token.openid, token.scope, token.create_at], function (err, result) {
        return callback(err);
    });
});
```

亲测，mongodb， mysql 均正常可用！

**Comment by JacksonTian** [comment]
正解。给你什么就存什么。

**Comment by JacksonTian** [comment]
我把你的示例代码加到README中。
